---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: knative-operator 
  namespace: knative-operator 
spec:
  interval: 24h
  url: https://knative.github.io/operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator 
  namespace: knative-operator
spec:
  interval: 30m
  chart:
    spec: knative-operator
    chart: 
    version: "1.x"
    sourceRef:
      kind: HelmRepository
      name: knative-operator 
      namespace: knative-operator
    interval: 12h
  values:
    installCRDs: true
